version: '3.4'

services:
  ordersapiapp:
    container_name: application
    image: ${DOCKER_REGISTRY-}ordersapiapp
    ports:
        - 5005:443
        - 8080:80 
    build:
      context: .
      dockerfile: OrdersApiApp/Dockerfile
    networks: 
        - internal

  database:
        image: postgres:latest
        container_name: order_db_postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - 5433:5432 
        networks: 
            - internal

networks:
  internal:
    driver: bridge  
  

  
